/** Teaching-line compatibility path for the Python `tools.base` module. */
export {
  AutoGeneratedTool,
  FunctionTool,
  Tool,
  expandableTool,
  toolAction,
  toolParameterSchema
} from './tool.js';
export type {
  ExpandableTool,
  FunctionToolOptions,
  OpenAIToolSchema,
  ToolActionDecorator,
  ToolActionMetadata,
  ToolOptions,
  ToolParameter
} from './tool.js';
