import { z } from 'zod';

import { ToolError } from '../core/errors.js';
import { ToolErrorCode } from './errors.js';
import { ToolResponse } from './response.js';

/** Python-compatible parameter metadata. `default` is always serialized, including null. */
export const toolParameterSchema = z
  .object({
    name: z.string().min(1),
    type: z.string().min(1),
    description: z.string(),
    required: z.boolean().default(true),
    default: z.unknown().nullable().default(null)
  })
  .strict();
export type ToolParameter = z.input<typeof toolParameterSchema>;
type ResolvedToolParameter = z.output<typeof toolParameterSchema>;

export interface OpenAIToolSchema {
  readonly type: 'function';
  readonly function: {
    readonly name: string;
    readonly description: string;
    readonly parameters: Record<string, unknown>;
  };
}

export interface ToolOptions<TSchema extends z.ZodType> {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: TSchema;
  readonly parameters?: readonly ToolParameter[];
  readonly jsonSchema?: Record<string, unknown>;
  readonly expandable?: boolean;
}

export interface ExpandableTool {
  readonly name: string;
  readonly description: string;
  readonly expandable: true;
  getExpandedTools(): readonly Tool[] | undefined;
}

export interface ToolActionMetadata {
  readonly _is_tool_action: true;
  readonly _tool_name?: string;
  readonly _tool_description?: string;
}

export type ToolActionDecorator = <T extends (...args: never[]) => unknown>(
  target: T
) => T & ToolActionMetadata;

function schemaHasUnsupportedNode(schema: z.ZodType): boolean {
  const seen = new WeakSet<object>();
  const visit = (value: unknown): boolean => {
    if (value === null || typeof value !== 'object') return false;
    if (seen.has(value)) return false;
    seen.add(value);
    if ('type' in value && typeof value.type === 'string') {
      if (['date', 'map', 'set', 'transform'].includes(value.type)) return true;
    }
    return Object.values(value).some(visit);
  };
  return visit(schema._zod.def);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

/** Base tool with structured execution responses and Python-style expandable actions. */
export abstract class Tool<TSchema extends z.ZodType = z.ZodType> {
  public readonly name: string;
  public readonly description: string;
  public readonly inputSchema: TSchema;
  public readonly parameters: readonly ResolvedToolParameter[];
  public readonly expandable: boolean;
  private readonly jsonSchema: Record<string, unknown> | undefined;

  protected constructor(options: ToolOptions<TSchema>) {
    this.name = options.name;
    this.description = options.description;
    this.inputSchema = options.inputSchema;
    this.parameters = (options.parameters ?? []).map((parameter) =>
      toolParameterSchema.parse(parameter)
    );
    this.jsonSchema = options.jsonSchema;
    this.expandable = options.expandable ?? false;
  }

  protected abstract run(input: z.output<TSchema>): ToolResponse | Promise<ToolResponse>;

  /**
   * Discover decorated instance methods on expandable subclasses. TypeScript has
   * no runtime parameter reflection, so generated actions accept an object and
   * pass it as the method's sole argument.
   */
  public getExpandedTools(): readonly Tool[] | undefined {
    if (!this.expandable) return undefined;
    const actions: Tool[] = [];
    const seen = new Set<string>();
    const sources: object[] = [this];
    let prototype: object | null = Object.getPrototypeOf(this);
    while (prototype && prototype !== Tool.prototype) {
      sources.push(prototype);
      prototype = Object.getPrototypeOf(prototype);
    }
    for (const source of sources) {
      for (const key of Object.getOwnPropertyNames(source)) {
        if (key === 'constructor' || seen.has(key)) continue;
        seen.add(key);
        const method = Object.getOwnPropertyDescriptor(source, key)?.value;
        if (typeof method !== 'function' || !isToolAction(method)) continue;
        actions.push(
          new AutoGeneratedTool({
            parent: this,
            method,
            inputSchema: z.object({}).passthrough(),
            ...(method._tool_name === undefined ? {} : { name: method._tool_name }),
            ...(method._tool_description === undefined
              ? {}
              : { description: method._tool_description })
          })
        );
      }
    }
    return actions.length ? actions : undefined;
  }

  protected unhandledErrorCode(): string {
    return ToolErrorCode.INTERNAL_ERROR;
  }

  protected unhandledErrorMessage(error: unknown): string {
    return `工具执行时发生未处理的异常: ${error instanceof Error ? error.message : String(error)}`;
  }

  public async execute(
    input: unknown,
    invocationContext: Record<string, unknown> = {}
  ): Promise<ToolResponse> {
    const parsed = this.inputSchema.safeParse(input);
    if (!parsed.success) {
      return ToolResponse.error(
        ToolErrorCode.INVALID_PARAM,
        `工具 '${this.name}' 参数无效: ${parsed.error.issues.map((issue) => issue.path.join('.') || '<root>').join(', ')}`,
        undefined,
        { ...invocationContext, params_input: input, tool_name: this.name }
      );
    }
    const start = performance.now();
    try {
      return this.withTiming(await this.run(parsed.data), input, start, invocationContext);
    } catch (error) {
      return ToolResponse.error(
        this.unhandledErrorCode(),
        this.unhandledErrorMessage(error),
        { time_ms: Math.trunc(performance.now() - start) },
        { ...invocationContext, params_input: input, tool_name: this.name }
      );
    }
  }

  public getParameters(): ResolvedToolParameter[] {
    return this.parameters.map((parameter) => ({ ...parameter }));
  }

  public toDict(): { name: string; description: string; parameters: ResolvedToolParameter[] } {
    return { name: this.name, description: this.description, parameters: this.getParameters() };
  }

  public async arun(
    input: unknown,
    invocationContext?: Record<string, unknown>
  ): Promise<ToolResponse> {
    return this.execute(input, invocationContext);
  }

  public toOpenAISchema(): OpenAIToolSchema {
    const parameters = this.jsonSchema ?? this.jsonSchemaFromZod();
    if (parameters.type !== 'object') {
      throw new ToolError(`Tool '${this.name}' input schema must produce a JSON Schema object`);
    }
    return {
      type: 'function',
      function: { name: this.name, description: this.description, parameters }
    };
  }

  private jsonSchemaFromZod(): Record<string, unknown> {
    if (schemaHasUnsupportedNode(this.inputSchema)) {
      throw new ToolError(
        `Tool '${this.name}' contains a Zod type that cannot be losslessly represented as JSON Schema; provide jsonSchema explicitly`
      );
    }
    try {
      const result = z.toJSONSchema(this.inputSchema);
      if (!isRecord(result))
        throw new ToolError(`Tool '${this.name}' produced an invalid JSON Schema`);
      return result;
    } catch (error) {
      if (error instanceof ToolError) throw error;
      throw new ToolError(`Tool '${this.name}' schema cannot be converted to JSON Schema`, error);
    }
  }

  private withTiming(
    response: ToolResponse,
    input: unknown,
    start: number,
    invocationContext: Record<string, unknown>
  ): ToolResponse {
    return ToolResponse.fromObject({
      ...response.toJSON(),
      stats: { ...(response.stats ?? {}), time_ms: Math.trunc(performance.now() - start) },
      context: {
        ...invocationContext,
        ...(response.context ?? {}),
        params_input: input,
        tool_name: this.name
      }
    });
  }
}

function isToolAction(
  value: unknown
): value is ((input: Record<string, unknown>) => unknown) & ToolActionMetadata {
  return (
    typeof value === 'function' && (value as Partial<ToolActionMetadata>)._is_tool_action === true
  );
}

export interface FunctionToolOptions<TSchema extends z.ZodType> extends ToolOptions<TSchema> {
  readonly handler: (input: z.output<TSchema>) => unknown | Promise<unknown>;
}

export class FunctionTool<TSchema extends z.ZodType = z.ZodType> extends Tool<TSchema> {
  private readonly handler: (input: z.output<TSchema>) => unknown | Promise<unknown>;
  public constructor(options: FunctionToolOptions<TSchema>) {
    super(options);
    this.handler = options.handler;
  }
  protected override async run(input: z.output<TSchema>): Promise<ToolResponse> {
    const output = await this.handler(input);
    return ToolResponse.success(String(output), { output });
  }
  protected override unhandledErrorCode(): string {
    return ToolErrorCode.EXECUTION_ERROR;
  }
  protected override unhandledErrorMessage(error: unknown): string {
    return `函数执行失败: ${error instanceof Error ? error.message : String(error)}`;
  }
}

export function toolAction<TSchema extends z.ZodType>(
  options: FunctionToolOptions<TSchema>
): FunctionTool<TSchema>;
export function toolAction(name?: string, description?: string): ToolActionDecorator;
export function toolAction<TSchema extends z.ZodType>(
  optionsOrName: FunctionToolOptions<TSchema> | string = '',
  description?: string
): FunctionTool<TSchema> | ToolActionDecorator {
  if (typeof optionsOrName === 'object') return new FunctionTool(optionsOrName);
  return ((target: (...args: never[]) => unknown) => {
    Object.defineProperties(target, {
      _is_tool_action: { value: true, enumerable: false },
      _tool_name: { value: optionsOrName || undefined, enumerable: false },
      _tool_description: { value: description, enumerable: false }
    });
    return target as typeof target & ToolActionMetadata;
  }) as ToolActionDecorator;
}

/** Generated action preserving its original parent's `this` receiver. */
export class AutoGeneratedTool<TSchema extends z.ZodType = z.ZodType> extends Tool<TSchema> {
  private readonly parent: object;
  private readonly method: (input: z.output<TSchema>) => unknown | Promise<unknown>;
  public constructor(options: {
    readonly parent: Tool | { readonly name: string };
    readonly method: (input: z.output<TSchema>) => unknown | Promise<unknown>;
    readonly name?: string;
    readonly description?: string;
    readonly inputSchema: TSchema;
    readonly parameters?: readonly ToolParameter[];
  }) {
    const metadata = options.method as typeof options.method & Partial<ToolActionMetadata>;
    const methodName = options.method.name.replace(/^_+/, '') || 'action';
    super({
      name: options.name ?? metadata._tool_name ?? `${options.parent.name}_${methodName}`,
      description:
        options.description ?? metadata._tool_description ?? `执行 ${options.method.name}`,
      inputSchema: options.inputSchema,
      ...(options.parameters === undefined ? {} : { parameters: options.parameters })
    });
    this.parent = options.parent;
    this.method = options.method;
  }
  protected async run(input: z.output<TSchema>): Promise<ToolResponse> {
    const output = await this.method.call(this.parent, input);
    return ToolResponse.success(String(output), { output });
  }
  protected override unhandledErrorCode(): string {
    return ToolErrorCode.EXECUTION_ERROR;
  }
}

class ToolGroup implements ExpandableTool {
  public readonly expandable = true as const;
  public constructor(
    public readonly name: string,
    public readonly description: string,
    private readonly tools: readonly Tool[]
  ) {}
  public getExpandedTools(): readonly Tool[] {
    return this.tools;
  }
}
export function expandableTool(options: {
  readonly name: string;
  readonly description: string;
  readonly tools: readonly Tool[];
}): ExpandableTool {
  return new ToolGroup(options.name, options.description, options.tools);
}
