import { describe, expect, test } from 'bun:test';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { z } from 'zod';

import {
  AsyncToolExecutor,
  AutoGeneratedTool,
  CalculatorTool,
  FunctionTool,
  NoteTool,
  SearchTool,
  TerminalTool,
  Tool,
  ToolChain,
  ToolErrorCode,
  ToolRegistry,
  ToolResponse,
  runParallelTools,
  toolAction
} from '../hello_agents/index.js';

class EchoTool extends Tool<typeof EchoTool.inputSchema> {
  public static readonly inputSchema = z.object({ input: z.string() }).strict();
  public constructor() {
    super({ name: 'echo', description: 'Echo input.', inputSchema: EchoTool.inputSchema });
  }
  protected run(input: z.output<typeof EchoTool.inputSchema>): ToolResponse {
    return ToolResponse.success(input.input);
  }
}

describe('learn-version tools', () => {
  test('supports registry lifecycle, direct functions, and generated actions', async () => {
    const registry = new ToolRegistry();
    registry.registerFunction('upper', 'Uppercase text.', (input) => input.toUpperCase());
    registry.register(new EchoTool());
    expect(registry.listTools()).toEqual(['upper', 'echo']);
    expect((await registry.execute('upper', 'hello')).text).toBe('HELLO');
    const generated = new AutoGeneratedTool({
      parent: { name: 'group' },
      method: (input: { value: string }) => input.value,
      name: 'group_value',
      description: 'Get value.',
      inputSchema: z.object({ value: z.string() }).strict()
    });
    registry.register(generated);
    expect((await registry.execute('group_value', { value: 'ok' })).text).toBe('ok');
    registry.unregister('echo');
    expect(registry.getTool('echo')).toBeUndefined();
    registry.clear();
    expect(registry.list()).toEqual([]);
  });

  test('keeps action metadata and calculator behavior', async () => {
    const action = toolAction('named_action', 'An action.');
    const method = action((value: string) => value);
    expect(method._is_tool_action).toBe(true);
    expect(method._tool_name).toBe('named_action');
    expect((await new CalculatorTool().execute({ input: 'sqrt(16) + 2' })).data.result).toBe(6);
    expect((await new CalculatorTool().execute({ input: 'bad()' })).errorInfo?.code).toBe(
      ToolErrorCode.EXECUTION_ERROR
    );
  });

  test('does not network by default and supports deterministic mocked search', async () => {
    const unavailable = await new SearchTool().execute({ input: 'hello' });
    expect(unavailable.text).toContain('网络搜索未启用');
    const mocked = new SearchTool({
      backend: 'duckduckgo',
      duckduckgoSearch: () => ({
        results: [{ title: 'Example', url: 'https://example.test', content: 'content' }],
        backend: 'duckduckgo',
        answer: null,
        notices: []
      })
    });
    expect((await mocked.execute({ input: 'hello', mode: 'structured' })).data).toMatchObject({
      backend: 'duckduckgo'
    });
  });

  test('persists notes and keeps terminal inside the workspace', async () => {
    const workspace = await mkdtemp(join(tmpdir(), 'helloagents-learn-tools-'));
    try {
      const notes = new NoteTool({ workspace });
      const created = await notes.execute({ action: 'create', title: 'Title', content: 'Body' });
      expect(created.text).toContain('笔记创建成功');
      const id = String(created.data.id);
      expect((await notes.execute({ action: 'read', note_id: id })).text).toContain('Body');
      expect((await notes.execute({ action: 'search', query: 'body' })).text).toContain('Title');
      expect((await notes.execute({ action: 'delete', note_id: id })).text).toContain('笔记已删除');
      const terminal = new TerminalTool({ workspace });
      await writeFile(join(workspace, 'hello.txt'), 'hello', 'utf8');
      expect((await terminal.execute({ command: 'cat hello.txt' })).text).toBe('hello');
      expect((await terminal.execute({ command: 'node -e "bad"' })).errorInfo?.code).toBe(
        ToolErrorCode.ACCESS_DENIED
      );
      expect((await terminal.execute({ command: 'cat ../secret' })).errorInfo?.code).toBe(
        ToolErrorCode.ACCESS_DENIED
      );
      expect((await terminal.execute({ command: 'cat hello.txt; echo bad' })).errorInfo?.code).toBe(
        ToolErrorCode.ACCESS_DENIED
      );
    } finally {
      await rm(workspace, { recursive: true, force: true });
    }
  });

  test('chains templates and executes bounded parallel batches in input order', async () => {
    const registry = new ToolRegistry().registerFunction(
      new FunctionTool({
        name: 'echo',
        description: 'Echo.',
        inputSchema: z.object({ input: z.string() }).strict(),
        handler: ({ input }) => input
      })
    );
    const chain = new ToolChain('demo', 'Demo');
    chain.addStep('echo', '{input}', 'out');
    expect(await chain.execute(registry, 'value')).toBe('value');
    const missingChain = new ToolChain('missing', 'Missing');
    missingChain.addStep('echo', '{missing}');
    expect(await missingChain.execute(registry, 'value')).toContain('模板变量替换失败');
    const executor = new AsyncToolExecutor(registry, 2);
    expect(
      (await executor.executeToolsBatch('echo', ['a', 'b'])).map((item) => item.result)
    ).toEqual(['a', 'b']);
    executor.close();
    expect(
      (
        await runParallelTools(registry, [
          { tool_name: 'echo', input_data: 'one' },
          { tool_name: 'echo', input_data: 'two' }
        ])
      ).map((item) => item.result)
    ).toEqual(['one', 'two']);
  });
});
