/**
 * HelloAgents TypeScript 教学版公共包入口（#81 入口收敛）。
 *
 * 根入口只导出教学符号：与上游 `hello_agents/__init__.py` 对应的核心/Agent/工具
 * 符号，以及上游子包中的教学能力（memory / context / utils / tools 等）。
 * 1.x 专属能力（Session 持久化、Skills、subagents、TodoWrite/DevLog、文件工具、
 * SSE、provider 适配器等）不属于教学面，不在此导出；对应文件保留供内部引用与
 * 回归测试。子路径入口：`@junlang-7/helloagents/{agents,context,core,memory,
 * tools,utils}`。WorkingMemory 为教学版 `memory` 实现（1.x 同名实现不冒充）。
 */
import pkg from '../package.json' with { type: 'json' };

export {
  AgentError,
  AgentException,
  ConfigError,
  ConfigException,
  HelloAgentsError,
  HelloAgentsException,
  LLMAbortError,
  LLMError,
  LLMException,
  LLMTimeoutError,
  ToolError,
  ToolException
} from './core/errors.js';
export { HelloAgentsLLM, SUPPORTED_PROVIDERS } from './core/llm.js';
export type { HelloAgentsLLMOptions, LLMInvokeOptions, SupportedProvider } from './core/llm.js';
export { MockAdapter } from './adapters/mock.js';
export type {
  AdapterCallOptions,
  AdapterConfig,
  AdapterRequest,
  AdapterToolRequest,
  BaseLLMAdapter,
  LLMAdapterFactory,
  LLMMessage,
  ToolChoice
} from './adapters/base.js';
export {
  Config,
  configSchema,
  createConfig,
  createConfigFromEnv,
  parseConfig
} from './core/config.js';
export type { ConfigInput, ConfigValues, ResolvedConfig } from './core/config.js';
export { Message, messageRoleSchema, messageSchema } from './core/message.js';
export type { MessageJSON, MessageRole } from './core/message.js';
export {
  LLMResponse,
  LLMToolResponse,
  StreamStats,
  llmResponseSchema,
  llmToolResponseSchema,
  parseLLMResponse,
  parseLLMToolResponse,
  parseStreamStats,
  streamStatsSchema,
  toolCallSchema
} from './core/responses.js';
export type { LLMResponseJSON, StreamStatsJSON, ToolCall } from './core/responses.js';
export {
  AgentEvent,
  ExecutionContext,
  agentEventSchema,
  eventTypeSchema
} from './core/lifecycle.js';
export type { AgentEventJSON, EventType, LifecycleHook } from './core/lifecycle.js';
export { ToolErrorCode, getAllToolErrorCodes, isToolErrorCode } from './tools/errors.js';
export type { ToolErrorCode as ToolErrorCodeValue } from './tools/errors.js';
export { ToolResponse, ToolStatus, toolResponseSchema } from './tools/response.js';
export type {
  ToolErrorInfo,
  ToolResponseJSON,
  ToolStatus as ToolStatusValue
} from './tools/response.js';
export {
  AutoGeneratedTool,
  FunctionTool,
  Tool,
  expandableTool,
  toolAction,
  toolParameterSchema
} from './tools/tool.js';
export type {
  ExpandableTool,
  FunctionToolOptions,
  OpenAIToolSchema,
  ToolActionDecorator,
  ToolActionMetadata,
  ToolOptions,
  ToolParameter
} from './tools/tool.js';
export { ToolRegistry, globalRegistry, global_registry } from './tools/registry.js';
export {
  ToolChain,
  ToolChainManager,
  createResearchChain,
  createSimpleChain,
  create_research_chain,
  create_simple_chain
} from './tools/chain.js';
export {
  AsyncToolExecutor,
  demo_parallel_execution,
  runBatchTool,
  runParallelTools,
  run_batch_tool,
  run_parallel_tools
} from './tools/async-executor.js';
export type { ToolTask, ToolTaskResult } from './tools/async-executor.js';
export { CalculatorTool, calculate } from './tools/builtin/calculator.js';
export {
  CHARS_PER_TOKEN,
  DEFAULT_MAX_RESULTS,
  SUPPORTED_BACKENDS,
  SUPPORTED_RETURN_MODES,
  SearchTool,
  search,
  searchHybrid,
  searchSerpapi,
  searchTavily,
  search_hybrid,
  search_serpapi,
  search_tavily
} from './tools/builtin/search-tool.js';
export type {
  FetchResponse,
  SearchBackend,
  SearchFetch,
  SearchPayload,
  SearchResult,
  SearchToolOptions
} from './tools/builtin/search-tool.js';
export { NoteTool } from './tools/builtin/note-tool.js';
export { TerminalTool } from './tools/builtin/terminal-tool.js';
export { TokenCounter } from './context/token-counter.js';
export type { TokenCounterOptions, TokenCounterStats } from './context/token-counter.js';
export {
  Logger,
  getLogger,
  get_logger,
  setupLogger,
  setup_logger,
  deserializeObject,
  deserialize_object,
  loadFromFile,
  load_from_file,
  saveToFile,
  save_to_file,
  serializeObject,
  serialize_object,
  ensureDir,
  ensure_dir,
  formatTime,
  format_time,
  getProjectRoot,
  get_project_root,
  mergeDicts,
  merge_dicts,
  safeImport,
  safe_import,
  validateConfig,
  validate_config
} from './utils/index.js';
export type { LogLevel, LoggerHandler, SerializationFormat } from './utils/index.js';
export { HistoryManager } from './context/history.js';
export type { HistoryManagerOptions } from './context/history.js';
export { ObservationTruncator } from './context/truncator.js';
export type {
  ObservationTruncatorOptions,
  TruncationReason,
  TruncationResult
} from './context/truncator.js';
export { WorkingMemory } from './memory/index.js';
export type { WorkingMemoryOptions } from './memory/types/working.js';
export { ContextBuilder, ContextConfig, ContextPacket, countTokens } from './context/builder.js';
export type {
  MemoryToolLike,
  RagToolLike,
  ContextBuilderOptions,
  BuildContextOptions,
  ContextPacketLike
} from './context/builder.js';
export { SimpleAgent } from './agents/simple-agent.js';
export type {
  AgentInvocationOptions,
  AgentLifecycleOptions,
  ParsedToolCall,
  SimpleAgentOptions
} from './agents/simple-agent.js';
export { FunctionCallAgent } from './agents/function-call-agent.js';
export type {
  FunctionCallAgentOptions,
  FunctionCallRunOptions
} from './agents/function-call-agent.js';
export { ToolAwareSimpleAgent } from './agents/tool-aware-agent.js';
export type { ToolAwareSimpleAgentOptions, ToolCallInfo } from './agents/tool-aware-agent.js';
export { Agent } from './core/agent.js';
export {
  DEFAULT_REACT_PROMPT,
  ReActAgent,
  parseReActAction,
  parseReActActionInput,
  parseReActOutput
} from './agents/react-agent.js';
export type { ReActAgentOptions } from './agents/react-agent.js';
export { DEFAULT_PROMPTS, Memory, ReflectionAgent } from './agents/reflection-agent.js';
export type {
  ReflectionAgentOptions,
  ReflectionPrompts,
  ReflectionRecord
} from './agents/reflection-agent.js';
export {
  DEFAULT_EXECUTOR_PROMPT,
  DEFAULT_PLANNER_PROMPT,
  Executor,
  INVALID_PLAN_ANSWER,
  PlanAndSolveAgent,
  Planner,
  parsePlan
} from './agents/plan-solve-agent.js';
export type {
  ExecutorOptions,
  PlanAndSolveAgentOptions,
  PlannerOptions
} from './agents/plan-solve-agent.js';
export {
  TraceLogger,
  createTraceHooks,
  traceEventSchema,
  withTraceFinalization
} from './observability/trace-logger.js';
export type { TraceEvent, TraceLoggerOptions, TraceStats } from './observability/trace-logger.js';
export { MemoryTool } from './tools/builtin/memory-tool.js';
export type { MemoryToolOptions } from './tools/builtin/memory-tool.js';
export { RAGTool } from './tools/builtin/rag-tool.js';
export type { RagLlmLike, RagLlmMessage, RAGToolOptions } from './tools/builtin/rag-tool.js';

export const version = pkg.version;
export {
  __author__,
  __description__,
  __email__,
  __version__,
  author,
  description,
  email
} from './version.js';

export const metadata = Object.freeze({
  name: '@junlang-7/helloagents',
  upstream: 'https://github.com/jjyaoao/HelloAgents',
  license: 'CC-BY-NC-SA-4.0'
});
